"""empty message

Revision ID: c66546ecc9b3
Revises: 502104b43819
Create Date: 2025-02-21 10:48:45.351940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66546ecc9b3'
down_revision = '502104b43819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['people.id'], name='favorite_people_name_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_people_pkey')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['planets.id'], name='favorite_planets_name_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_planets_pkey')
    )
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    # ### end Alembic commands ###
